name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation. You point, the Agent reasons."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form triggers an autonomous agent investigation.*

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      options:
        - "Atomic (Quick check, specific question)"
        - "Long-Form (Deep distillation, multi-file synthesis)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target (Repository or Document)
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  - type: textarea
    id: intent
    attributes:
      label: Strategic Intent / The "Why"
      description: What are you trying to achieve? (e.g., "Audit for security risks," "Understand why this is complex," "Capture lessons for the new team.")
      placeholder: "We are scaling up and I'm worried this architecture won't hold."
    validations:
      required: true

  - type: textarea
    id: special-requests
    attributes:
      label: Special Requests / Observations (Optional)
      description: Any specific clues or symptoms you noticed?
      placeholder: "e.g., 'I feel like this code is too hard to test.'"
