name: "🧠 Conceptual Investigation Intake"
description: "Initiate an autonomous AI investigation. You point, the Agent reasons."
title: "[Intake]: "
labels: ["investigation", "autonomous-agent"]
body:
  - type: markdown
    attributes:
      value: |
        # Project Wisdom Intake
        *This form triggers an autonomous agent investigation.*

  - type: dropdown
    id: analysis-type
    attributes:
      label: Investigation Depth
      options:
        - "Atomic (Quick check, specific question)"
        - "Long-Form (Deep distillation, multi-file synthesis)"
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target (Repository or Document)
      placeholder: "https://github.com/my-org/my-repo"
    validations:
      required: true

  - type: input
    id: subject
    attributes:
      label: Subject / Theme
      description: What are we looking at? (e.g., "The Payment Gateway", "The Auth Service", "The Team Culture")
      placeholder: "Auth Service"
    validations:
      required: true

  - type: checkboxes
    id: menu-items
    attributes:
      label: The Wisdom Ladder (Methodologies)
      description: Select the tools. The Agent will determine how to apply them to your Subject.
      options:
        - label: "Level 1: Hard Architecture Mapping (The Structure)"
        - label: "Level 2: Decision Forensics (The History)"
        - label: "Level 2: Anti-Library Extraction (The Failures)"
        - label: "Level 3: Vision Alignment (Intent vs. Reality)"
        - label: "Level 3: Process Memory (The Rationale)"
        - label: "Level 4: Meta-Pattern Synthesis (The Patterns)"
        - label: "Level 4: Paradigm Extraction (The Mental Models)"
    validations:
      required: true

  - type: textarea
    id: special-requests
    attributes:
      label: Special Requests / Observations (Optional)
      description: Did you see something specific? A weird bug? A feeling of complexity? (The Agent uses this as a clue, not a rule.)
      placeholder: "e.g., 'I feel like this code is too hard to test.'"
